export const GET_CATEGORY_BY_BUSINESS = 'GET_CATEGORY_BY_BUSINESS'
export const POST_CATEGORY = 'POST_CATEGORY'
export const PUT_CATEGORY = 'PUT_CATEGORY'
export const INIT_VALUE_CATEGORY = 'INIT_VALUE_CATEGORY'