export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY'
export const POST_SUB_CATEGORY = 'POST_SUB_CATEGORY'
export const PUT_SUB_CATEGORY = 'PUT_SUB_CATEGORY'
export const INIT_VALUE_SUB_CATEGORY = 'INIT_VALUE_SUB_CATEGORY'