const EVENT_POST_APPOINTMENT = 'EVENT_POST_APPOINTMENT';
const EVENT_PUT_APPOINTMENT = 'EVENT_PUT_APPOINTMENT';
const EVENT_DELETE_APPOINTMENT = 'EVENT_DELETE_APPOINTMENT';

module.exports = {
    EVENT_POST_APPOINTMENT,
    EVENT_PUT_APPOINTMENT,
    EVENT_DELETE_APPOINTMENT,
  };